
-- Query 1: Count active users per subscription plan
-- Business Goal: Identify which plan has the highest number of currently active users

SELECT 
    plan_name,
    count(user_id) AS total_subscription
FROM subscriptions s
JOIN plans p
ON p.plan_id = s.plan_id
WHERE STATUS = "active"
GROUP BY p.plan_id   

-- Query 2: Calculate monthly revenue generated by each subscription plan
-- Business Goal: Identify which plan contributes most to monthly revenue

SELECT 
    plan_name,
    COUNT(subscription_id) as ACTIVE_users,
    price AS monthly_price ,
    COUNT(user_id) * price AS revenue
FROM plans p
JOIN subscriptions s
ON s.plan_id = p.plan_id
WHERE STATUS = "active"
GROUP BY plan_name
ORDER BY revenue DESC ; 

-- Query 3: Identify active subscribers who never watched any content
-- Business Goal: Find disengaged users who are at high risk of churn

SELECT
    u.user_id ,
    u.name,
    u.email,
    u.country,
    s.start_date
from users u
JOIN  subscriptions s
    ON s.user_id = u.user_id
WHERE u.user_id NOT IN (
    SELECT user_id FROM watch_history)
    AND s.`status` = "active"
ORDER BY start_date ;

-- Query 4: Identify active users who have been inactive for the last 30 days
-- Business Goal: Detect users at high risk of churn due to inactivity

SELECT 
    u.user_id,
    NAME,
    email,
    country,
    MAX(watch_date) AS last_watch_date
FROM USERs u
left JOIN watch_history w
    ON w.user_id = u.user_id
JOIN subscriptions s
    ON s.user_id = u.user_id
WHERE s.`status` = "active "
GROUP BY u.user_id
HAVING last_watch_date IS NULL or
       last_watch_date <DATE_SUB(CURDATE(),INTERVAL 30 DAY)
ORDER BY last_watch_date;

-- Query 6: Calculate average watch time per genre
-- Business Goal: Identify genres that generate higher user engagement

SELECT 
    c.genre,
    AVG(watch_minutes) AS average_watch_min_per_genre
FROM content c
JOIN watch_history h
ON c.content_id = h.content_id
GROUP BY c.genre
ORDER BY average_watch_min_per_genre DESC;

-- Query 7: Calculate completion rate for each content
-- Business Goal: Measure how often users finish the content they start

SELECT 
    c.content_id ,
    title, 
    COUNT(watch_id) AS total_viwes,
    ROUND(
       SUM(completed) / COUNT(watch_id) *100 
       ,2) AS complection_presentag
FROM watch_history w
JOIN content c
ON c.content_id = w.content_id
GROUP BY content_id 
ORDER BY complection_presentag DESC;

-- Query 8: Identify top 10 power users by total watch time
-- Business Goal: Find users with highest engagement on the platform

SELECT 
    u.user_id ,
    NAME, 
    country,
    SUM(watch_minutes) AS total_watching
FROM users u
JOIN watch_history w
ON w.user_id = u.user_id
GROUP BY user_id 
ORDER BY total_watching DESC
LIMIT 10 ;

-- Query 9 (Optimized Version with Single CTE)
-- Business Goal: Identify most watched genre per country
-- Approach: Aggregate + Rank inside one CTE

WITH ranked_genres AS (
    SELECT
        u.country,                              -- User country
        c.genre,                                -- Content genre
        SUM(w.watch_minutes) AS total_watch_minutes,
        RANK() OVER (
            PARTITION BY u.country
            ORDER BY SUM(w.watch_minutes) DESC
        ) AS genre_rank                         -- Rank genres per country
    FROM watch_history w
    JOIN users u
        ON w.user_id = u.user_id
    JOIN content c
        ON w.content_id = c.content_id
    GROUP BY u.country, c.genre
)

SELECT
    country,
    genre AS most_watched_genre,
    total_watch_minutes
FROM ranked_genres
WHERE genre_rank = 1
ORDER BY country;SELECT 
    country,
    genre,
    total_watch_time
FROM 
(SELECT genre,
        country,
        SUM(watch_minutes) AS total_watch_time,
        RANK() OVER(partition BY country ORDER BY SUM(watch_minutes) ) AS rank_
    FROM USERs u
    JOIN watch_history h
    ON u.user_id =h.user_id
    JOIN content c
    ON c.content_id= h.content_id
    GROUP BY country , genre) t
WHERE t.RANK_ = 1
ORDER BY t.country


-- Query 10: Identify high-rated but low-engagement content
-- Business Goal: Find quality content that is underperforming in watch time

WITH content_metrics AS (
    SELECT
        c.content_id,                                -- Unique content ID
        c.title,                                     -- Content title
        ROUND(AVG(r.rating), 2) AS avg_rating,       -- Average rating
        SUM(w.watch_minutes) AS total_watch_time     -- Total watch time
    FROM content c
    LEFT JOIN ratings r
        ON c.content_id = r.content_id               -- Join ratings
    LEFT JOIN watch_history w
        ON c.content_id = w.content_id               -- Join watch data
    GROUP BY c.content_id, c.title
)

SELECT
    content_id,
    title,
    avg_rating,
    total_watch_time
FROM content_metrics
WHERE avg_rating >= 4                                -- High-rated content
  AND total_watch_time < (
        SELECT AVG(total_watch_time) 
        FROM content_metrics
      )                                              -- Below average watch time
ORDER BY avg_rating DESC;

-- 10 . identify the churn rate of the customr

SELECT 
    DATE_FORMAT(end_date, "%y-%m") AS MONTH,
    ROUND(COUNT(*)/(SELECT count(*) FROM subscriptions)*100, 2) AS churn_rate 
FROM subscriptions
WHERE STATUS = "cancelled"
GROUP BY month
ORDER BY month

-- Query 12: Calculate monthly revenue lost due to churn
-- Business Goal: Measure financial impact of subscription cancellations

SELECT
    DATE_FORMAT(s.end_date, '%Y-%m') AS cancellation_month,  -- Month of cancellation
    COUNT(s.subscription_id) AS cancelled_users,             -- Number of cancellations
    SUM(p.price) AS revenue_lost                             -- Total monthly revenue lost
FROM subscriptions s
JOIN plans p
    ON s.plan_id = p.plan_id                                 -- Join to get plan price
WHERE s.status = 'Cancelled'                                 -- Only cancelled subscriptions
GROUP BY DATE_FORMAT(s.end_date, '%Y-%m')
ORDER BY cancellation_month;

-- Query 13: Calculate retention rate by subscription plan
-- Business Goal: Identify which plan retains users best

SELECT
    p.plan_name,                                         -- Subscription plan name

    COUNT(s.subscription_id) AS total_subscriptions,     -- Total users who subscribed

    SUM(CASE 
            WHEN s.status = 'Active' THEN 1 
            ELSE 0 
        END) AS active_users,                            -- Currently active users

    ROUND(
        (SUM(CASE 
                WHEN s.status = 'Active' THEN 1 
                ELSE 0 
             END) 
         / COUNT(s.subscription_id)) * 100,
        2
    ) AS retention_rate_percentage                       -- Retention %
FROM subscriptions s
JOIN plans p
    ON s.plan_id = p.plan_id
GROUP BY p.plan_name
ORDER BY retention_rate_percentage DESC;

-- Query 14: Detect plan upgrades and downgrades
-- Business Goal: Track user subscription movement between plans

WITH user_plan_history AS (
    SELECT
        s.user_id,                          -- User ID
        s.start_date,                       -- Subscription start date
        p.plan_name,                        -- Current plan
        p.price,                            -- Current plan price

        LAG(p.plan_name) OVER (
            PARTITION BY s.user_id
            ORDER BY s.start_date
        ) AS previous_plan,

        LAG(p.price) OVER (
            PARTITION BY s.user_id
            ORDER BY s.start_date
        ) AS previous_price

    FROM subscriptions s
    JOIN plans p
        ON s.plan_id = p.plan_id
)

SELECT
    user_id,
    previous_plan,
    plan_name AS current_plan,
    previous_price,
    price AS current_price,

    CASE
        WHEN previous_price IS NULL THEN 'First Subscription'
        WHEN price > previous_price THEN 'Upgrade'
        WHEN price < previous_price THEN 'Downgrade'
        ELSE 'No Change'
    END AS subscription_change_type

FROM user_plan_history
WHERE previous_price IS NOT NULL
ORDER BY user_id, start_date;

